services:
  spring-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-server
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://${DB_SERVER}:5432/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASS}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      EMOTION_PROFILE_PATH: /app/config/emotion_profiles.json
    volumes:
      - config/emotion_profiles.json:/app/config/emotion_profiles.json
    depends_on:
      - elasticsearch
    networks:
      - prod_server
networks:
  prod_server:
    driver: bridge



